### ISSUE TITLE
Crash when the game start

### ISSUE THREAD

**Issue by Theduskofdeath** [Chicken-Bones/CodeChickenLib#56]
I have some errors (with CodeChickenLib) when i launch the game

Forge version : 10.13.4.1614 (I've tested with the recommanded version i still have the crash)
Java 8
Log : http://paste.ee/p/nEcU0

**Comment by adegarimore** [comment]
From the bottom of my heart. Thanks you for posting the resolution when you closed the issue. You could have easily said "Nvm. I fixed it." but instead you decided to say "I resolved the issue. This was the problem" Please continue to set a good example to others by posting what the problem was and how it was resolved when you close an issue :)
